name: BanSystem-Spigot
author: Papiertuch
version: 1.4
main: de.einjava.bansystem.BanSystem
commands:
  ban:
  ban-reduce:
  check:
  history:
  kick:
  mute:
  mute-reduce:
  login:
  unban:
  unmute: